title: Hallucinations of a programmer mind
description: My Personal blogs about everything
author: Amin Taheri
github: https://github.com/amintaheri23
about: I'm thinker
disqus_shortname: amintaheriblog
google_analytics: UA-174954679-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/amin.taheri.982/"
    - icon: fa-twitter
      link: "https://twitter.com/sed_amin"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/sed-amin-taheri"
    - icon: fa-stack-exchange
      link: "https://stackoverflow.com/users/8495032/amin-taheri"
    - icon: fa-github
      link: "https://github.com/amintaheri23"

share:
  twitter_username: sed_amin
  fb_appid: 0

urls:
    - text: About Me
      url: /blog/about/
    - text: My Projects
      url: /blog/projects/
    - text: XML Feed
      url: /blog/feed.xml

url: "https://amintaheri23.github.io/blog"
baseurl: "/blog"
paginate: 20
per_page: 20
paginate_path: "/blog/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
